//
//  ViewController.swift
//  Am I an MLM?
//
//  Created by Ian Schrauth on 6/15/22.
//

import UIKit

class ViewController: UIViewController {
    
    let MLMCompanies_regular = ["31",
                                "5LINX",
                                "ABBY & ANNA",
                                "ACAN PACIFIC",
                                "ACN",
                                "ACTILABS",
                                "ADORNABLE(DOT)U",
                                "ADVOCARE",
                                "AEROGROW",
                                "AGNES & DORA",
                                "AIM GLOBAL",
                                "AKASUKA (JAPAN)",
                                "ALCONE",
                                "ALICE'S TABLE",
                                "ALL'ASTA",
                                "ALLYSIAN SCIENCES",
                                "ALOE VERA OF",
                                "ALOETTE",
                                "ALPHAY INT",
                                "ALUREVE",
                                "AMARE GLOBAL",
                                "AMBIT",
                                "AMELIA JAMES",
                                "AMEO",
                                "AMERICAN INCOME LIFE",
                                "AMSOIL",
                                "AMWAY",
                                "ANN SUMMERS",
                                "ANN SUMMERS (UK)",
                                "ANORAK (UK)",
                                "ANRAN (CHINA)",
                                "APOLLO (INDIA)",
                                "APRIORI",
                                "AQUASOURCE UK",
                                "ARBONNE",
                                "ARIIX",
                                "ARSOA HONSHA (JAPAN)",
                                "ASEA GLOBAL",
                                "ASIRVIA (SHUT DOWN)",
                                "ASPIRE/DIGITAL ALTITUDE",
                                "ATC COIN",
                                "ATHENA'S",
                                "ATOMY",
                                "AVA ANDERSON",
                                "AVA ROSE",
                                "AVISAE",
                                "AVON",
                                "B:HIP GLOBAL",
                                "BACHAR NUTRITION",
                                "BAMBOO PINK",
                                "BAREFOOT BOOKS",
                                "BATH(DOT)OLOGIE",
                                "BEACH BODY",
                                "BEARCEREJU (JAPAN)",
                                "BEAUTICONTROL",
                                "BEAUTY COUNTER",
                                "BEAUTY SOCIETY",
                                "BECAUSE COSMETICS",
                                "BECOME INTERNATIONAL (US",
                                "BEDROOM KANDI",
                                "BEEVER (UK)",
                                "BELCORP (LATIN AMERICA)",
                                "BELLAME",
                                "BEMER",
                                "BETTER WAY DESIGN/IMPORTS",
                                "BIOGREEN ARGENTINA",
                                "BIOPERFORMANCE",
                                "BOD-E PRO",
                                "BODY BY VI/VISALUS",
                                "BODY SHOP AT",
                                "BOISSET COLLECTION",
                                "BOSTON FINNEY (SHUT",
                                "BOUNCE LIFE/NETWORK",
                                "BUD STAR (CANADA)",
                                "BURNLOUNGE (SHUT DOWN)",
                                "BUSKINS",
                                "BUTTERFLY BEAUTY",
                                "CABI",
                                "CAMBRIDGE WEIGHT PLAN/DIET",
                                "CAN",
                                "CAPTAIN TORTUE",
                                "CARICO INT",
                                "CELEBRATING HOME",
                                "CELLEMENTS",
                                "CEO MOVEMENT (NOT",
                                "CHALK COUTURE",
                                "CHALKY & CO",
                                "CHANDEAL (JAPAN)",
                                "CHARLE (JAPAN)",
                                "CHARLIE'S PROJECT",
                                "CHEF'S TOOLBOX (AUS)",
                                "CHERISH NATURAL PRODUCTS",
                                "CHLOE & ISABEL",
                                "CLEVER CONTAINER",
                                "CLOSE TO MY",
                                "CLOUD 9 PARTIES",
                                "COBRA GROUP/APPCO",
                                "COCOA EXCHANGE",
                                "COLOR BY AMBER",
                                "COLOR HAPPY",
                                "COLOR STREET",
                                "COLOUR ME BEAUTIFUL",
                                "COMPELLING CREATIONS",
                                "CONKLIN",
                                "COOKIE LEE (SHUT",
                                "COSWAY (MALAYSIA)",
                                "COUNTRY SCENTS",
                                "CREATE YOUR LIFE",
                                "CREATIVE MEMORIES",
                                "CREDIT REPAIR USA",
                                "CRUNCHI",
                                "CUTCO",
                                "CVSL",
                                "DAISY BLUE NATURALS",
                                "DAMSEL IN DEFENSE",
                                "DARCEYS",
                                "DAVID LERNER ASSOCIATES",
                                "DAZZLE AND DAZE",
                                "DEUTSCHE VERMÖGENSBERATUNG/DVAG (GERMANY)",
                                "DIANA (JAPAN)",
                                "DIONE COSMETICS",
                                "DIRECT CELLARS/DC NATION",
                                "DISCOVERY TOYS",
                                "DIVVEE/NUI",
                                "DOT DOT SMILE",
                                "DOTERRA",
                                "DU NORTHING DESIGNS",
                                "DUBLI NETWORK",
                                "DUDLEY BEAUTY",
                                "DXN",
                                "DYNAMIC ESSENTIALS",
                                "ECOWAREHOUSE",
                                "ELEPRENEUER",
                                "ELK RIVER SOAPS",
                                "ELLA TINA",
                                "ELLI KAI",
                                "ELVACITY",
                                "EMGOLDEX/GLOBAL INTERGOLD",
                                "ENAGIC/KANGEN WATER",
                                "ENDLESS XPRESSIONS",
                                "ENERSOURCE INT",
                                "ENJO (AUS)",
                                "ENVY JEWELRY",
                                "EPICURE (CANADA)",
                                "EQUINOX INTERNATIONAL (DISSOLVED",
                                "ERGO (GERMANY)",
                                "ESSANTE ORGANICS",
                                "ESSENTIAL BODYWEAR",
                                "EUROPEAN GROUPING OF",
                                "EUROPEAN HOME RETAIL",
                                "EVANESCENCE NETWORK",
                                "EVER SKINCARE",
                                "EVOLUTION TRAVEL",
                                "EVOLVHEALTH",
                                "FABERLIC (RUSSIA)",
                                "FAMILY FIRST LIFE",
                                "FAMILY HERITAGE INSURANCE",
                                "FANTASIA",
                                "FANTASIA (CANADA)",
                                "FARMASI",
                                "FES CONNECT",
                                "FIBI & CLO",
                                "FIFTH AVE COLLECTION",
                                "FIRST FITNESS NUTRITION",
                                "FIT4MOM",
                                "FITTEAM GLOBAL",
                                "FLAMINGO PAPERIE",
                                "FLEURESSE",
                                "FM WORLD (UK)",
                                "FOR TAILS ONLY",
                                "FOREVER LIVING",
                                "FOREX EDUCATION (IMARKETS)",
                                "FOREX ENTOURAGE",
                                "FORTUNE HI-TECH MARKETING",
                                "FOUR OCEANS",
                                "FRAGANT JEWELS",
                                "FREELIFE",
                                "FRONTROW",
                                "FUEL FREEDOM INT",
                                "FUND AMERICA (BANKRUPT",
                                "GANO EXCEL",
                                "GELMOMENT",
                                "GEMSTRA",
                                "GENESIS PURE",
                                "GLOBAL LEGACY INITIATIVE",
                                "GODESANA",
                                "GOLD CANYON",
                                "GOLDEN DAYS (CHINA)",
                                "GRACE & HEART",
                                "GREEN HORIZEN",
                                "GREETING CAKE COMPANY",
                                "H2O AT HOME",
                                "HALE",
                                "HANKY PANKY PARTIES",
                                "HAPPY COFFEE",
                                "HARVARD RISK MANAGEMENT",
                                "HAYWARD'S GOURMET POPCORN",
                                "HB NATURALS",
                                "HE(L)O",
                                "HEALTHY PEACH",
                                "HEAVENLY CHIA",
                                "HEKA CORP",
                                "HELO WRISTBANDS",
                                "HEMPWORX",
                                "HERBALIFE",
                                "HERITAGE MAKERS",
                                "HINODE",
                                "HOLIDAY MAGIC (SHUT",
                                "HOME INTERIORS",
                                "HONEY",
                                "HONEY & LACE",
                                "HUALIN BIOTECH (CHINA)",
                                "ICOINPRO",
                                "ID LIFE",
                                "IGNITING PASSION (CANADA)",
                                "IMARKETSLIVE",
                                "IMMUNOTEC",
                                "IMPERIAL CANDLES (UK)",
                                "IN A PIKLE",
                                "INCOME ADVANTAGE",
                                "INDIA HICKS",
                                "INFINITUS",
                                "INITIALS",
                                "INKD UP NAILS",
                                "INNOV8TIVE NUTRITION",
                                "INTELETRAVEL",
                                "INTIMO (AUS/NZ)",
                                "ISAGENIX",
                                "ITWORKS!",
                                "J(DOT) ELIZABETH",
                                "J(DOT) HILBURN",
                                "J(DOT)R WATKINS",
                                "JAFRA",
                                "JAMBERRY",
                                "JAMBY",
                                "JAMIE AT HOME",
                                "JANICE COLLECTION",
                                "JAVA MOMMA",
                                "JAVITA",
                                "JBLOOM",
                                "JEQUITI",
                                "JERKY DIRECT",
                                "JEUNESSE",
                                "JEWEL KADE (31)",
                                "JEWELSCENT",
                                "JK APPAREL (CANADA)",
                                "JORDAN ESSENTIALS",
                                "JOYMAIN (CHINA)",
                                "JOYOME (PLEXUS)",
                                "JUICEPLUS",
                                "JUMP NATURAL",
                                "KAESAR & BLAIR",
                                "KALAIA",
                                "KALO & CO",
                                "KANGEN WATER",
                                "KANNAWAY",
                                "KARAT BARS",
                                "KASZAZZ",
                                "KEEP COLLECTIVE",
                                "KEEP ME SAFE",
                                "KETO (PRUVIT)",
                                "KETO COFFEE",
                                "KETONES",
                                "KIRBY",
                                "KLEENEZE",
                                "KOBOLD (VORWERK)",
                                "KYANI",
                                "LABELLA BASKETS",
                                "LADY GODIVA BEAUTY",
                                "LAVYLITES",
                                "L'BRI",
                                "LEADUP CONSULTING",
                                "LEGAL SHIELD",
                                "LEGART (CANADA)",
                                "LEGEND AGE (CHINA)",
                                "LEGGING ARMY",
                                "LEGGING GIRL",
                                "LEMONGRASS SPA",
                                "LEREVE (CANADA)",
                                "LE-VEL (THRIVE)",
                                "LIA SOPHIA (DISSOLVED)",
                                "LIFE ABUNDANCE",
                                "LIFE LEADERSHIP",
                                "LIFE TREE WORLD",
                                "LIFEBROOK",
                                "LIFEPLUS (US/GERMANY)",
                                "LIFE'S ABUNDANCE",
                                "LIFEVANTAGE",
                                "LILLA ROSE",
                                "LIMELIFE",
                                "LIMU",
                                "LIMU",
                                "LINEN WORLD",
                                "LION CROWN",
                                "LIPSENSE",
                                "LIV INTERNATIONAL",
                                "LIVE SORE",
                                "LONGABEGER COMPANY",
                                "LONGRICH (CHINA)",
                                "LORRAINE LEE LINEN",
                                "LOVE WINX",
                                "LR BEAUTY &",
                                "LULAROE",
                                "LULU AVE",
                                "LUMINESS",
                                "LYCONET/LYONESS",
                                "LYONESS",
                                "M(DOT) GLOBAL (JAMBERRY)",
                                "M(DOT) NETWORK",
                                "MAELLE BEAUTY",
                                "MAGNABILITIES",
                                "MAGNOLIA & VINE",
                                "MAKEUP ERASER",
                                "MAN CAVE",
                                "MANNATECH",
                                "MARK(DOT)",
                                "MARKET AMERICA",
                                "MARLY RAY",
                                "MARVELOUS MOUSE TRAVELS",
                                "MARY & MARTHA",
                                "MARYKAY",
                                "MASKARA (NOW SEINT)",
                                "MATILDA JANE",
                                "MAX & MADELEINE",
                                "MAXWELL CLOTHING",
                                "MCA",
                                "MEDIFAST",
                                "MELALEUCA",
                                "METABOLIFE (DISSOLVED IN",
                                "MIA BATH AND",
                                "MIALISIA",
                                "MICHE EU",
                                "MIKI (ASIA)",
                                "MOA NUTRITION",
                                "MODERE",
                                "MOJILIFE",
                                "MONAT",
                                "MONAVIE (WENT INTO",
                                "MORINDA BIOACTIVES",
                                "MOTIVES COSMETICS",
                                "MULTPURE",
                                "MY CLUB 8",
                                "MY DAILY CHOICE",
                                "MY LALA LEGGINGS",
                                "MYECON",
                                "NATIONAL SAFETY ASSOCIATES",
                                "NATIONAL WEALTH CENTER",
                                "NATURA (BRAZIL)",
                                "NATURE DIRECT (AUS)",
                                "NATURE'S SUNSHINE PRODUCTS",
                                "NEAL'S YARD REMEDIES",
                                "NEOLIFE",
                                "NEORA (NERIUM)",
                                "NERIUM",
                                "NEVETICA",
                                "NEW ERA (CHINA)",
                                "NEW U LIFE",
                                "NEWAYS",
                                "NIKKEN",
                                "NOEVIR",
                                "NOMADES",
                                "NOONDAY COLLECTION",
                                "NORWEX",
                                "NOUVEAU RICHE (REAL",
                                "NSPIRE NETWORK",
                                "NUCERITY",
                                "NUSKIN",
                                "NUTRIBOOM",
                                "NXIVM",
                                "NYGARD",
                                "OMNILIFE",
                                "ONE HOPE WINE",
                                "OPTAVIA",
                                "OPULENZA",
                                "ORGANO GOLD",
                                "ORIFLAME",
                                "ORIGAMI OWL",
                                "OUR HEARTS DESIRE",
                                "PAID 2 SAVE",
                                "PAMPERED CHEF",
                                "PAPARAZZI",
                                "PAPERLY",
                                "PARK LANE JEWELRY",
                                "PARTY GIRL",
                                "PARTY LITE",
                                "PARTY TIME MIXES",
                                "PARTYLITE",
                                "PASSION PARTIES",
                                "PAWTREE",
                                "PAYCATION",
                                "PEACH",
                                "PEARL CHIC",
                                "PEEKABOO BEANS",
                                "PERFECT (CHINA)",
                                "PERFECTLY POLISHED",
                                "PERFECTLY POSH",
                                "PERSONALLY POETIC",
                                "PHP",
                                "PIERRE LANG",
                                "PINK ZEBRA",
                                "PIPHANY",
                                "PIXIELANE",
                                "PLEXUS",
                                "PLUMERIA BATH",
                                "PLUNDER",
                                "PM INTERNATIONAL",
                                "POLA (JAPAN)",
                                "POOFY ORGANICS",
                                "POWUR",
                                "PREMIER DESIGNS",
                                "PREMIER FINANCIAL",
                                "PRIMEMYBODY",
                                "PRIMERICA",
                                "PRINCESS HOUSE",
                                "PRODOULA",
                                "PROYOUNG",
                                "PRUVIT",
                                "PULSE COSMETICS",
                                "PURE HAVEN",
                                "PURE ROMANCE",
                                "PUREHAVEN",
                                "PURELY",
                                "PURIUM",
                                "QNET",
                                "QUANJIAN NATURAL (CHINA)",
                                "RADIANTLYYOU",
                                "RAIN INTERNATIONAL",
                                "RAINBOW VACUUM",
                                "REAL TIME PAIN",
                                "RED ASPEN",
                                "RED SAFETY",
                                "REGAL HOME AND",
                                "RELIV",
                                "RELIV",
                                "RENATUS REAL ESTATE",
                                "REVITALU",
                                "RIWAY",
                                "ROBERT KIYOSAKI",
                                "RODAN+FIELDS",
                                "ROLAND (VORWERK)",
                                "ROLMEX (CHINA)",
                                "ROYAL TONGAN LIMU",
                                "ROYALTIE GENS",
                                "RUBY RIBBON",
                                "SABA",
                                "SABIKA JEWELRY",
                                "SAFEGIRL SECURITY",
                                "SALAD MASTER",
                                "SARSO (INDIA)",
                                "SCENTSY",
                                "SCHNEIDER'S GOURMET WORLD",
                                "SCOUT & CELLAR",
                                "SEACRET",
                                "SEINT (FORMERLY MASKARA)",
                                "SENDOUTCARDS",
                                "SENEGENCE",
                                "SHAKEOLOGY (BEACHBODY)",
                                "SHAKLEE",
                                "SHOPPING SHERLOCK",
                                "SHRIMP & GRITS",
                                "SIGNATURE HOMESTYLES",
                                "SILPADA",
                                "SILVER ICING",
                                "SIMPLE MAN",
                                "SIMPLY SUCCESS ELITE",
                                "SIMPLYFUN GAMES",
                                "SKINNY BODY AT",
                                "SKINSANITY/TOMORROW'S LEAF",
                                "SMART CIRCLE",
                                "SMARTWAY",
                                "SOLAVEI (DISSOLVED 2015)",
                                "SOLVEI (BANKRUPT)",
                                "SOPHIE PARIS (FRANCE/ASIA)",
                                "SOUTH HILL DESIGNS",
                                "SOUTHERN LIVING AT",
                                "SOUTHWESTERN ADVANTAGE",
                                "SSEKO",
                                "STAMPIN UP",
                                "STEAM ENERGY",
                                "STEEPED TEA",
                                "STELLA & DOT",
                                "STREAM ENERGY",
                                "STYLE DOTS",
                                "SUCCESS UNIVERSITY",
                                "SUN HOPE (CHINA)",
                                "SUNRIDER",
                                "SUNSET GOURMET",
                                "SUNSHINE EMPIRE (DISSOLVED",
                                "SURGE 365",
                                "SWEET LEGS",
                                "SWEET MINERALS",
                                "SYMMETRY FINANCIAL GROUP",
                                "SYNTEK GLOBAL",
                                "T(DOT)O(DOT)P MARKETING GROUP",
                                "TAG TEAM MARKETING",
                                "TAISEI/GREEN PLANET/KAIKISUI (JAPAN_",
                                "TARA AT HOME",
                                "TASTEFULLY SIMPLE",
                                "TAVALA",
                                "TEALIGHTFUL",
                                "TEAM NATIONAL",
                                "TEDIVINA",
                                "TELECOM PLUS (UK)",
                                "TELEXFREE (BANKRUPT 2014)",
                                "THE ADVERT PLATFROM",
                                "THE BODY SHOP",
                                "THE LANDMARK FORUM",
                                "THE SUPER AFFILIATE",
                                "THERMOMIX (VORWERK)",
                                "THIRTY ONE",
                                "THRIVE",
                                "THRIVE LIFE",
                                "TIBER RIVER NATURALS",
                                "TKO WORLDWIDE",
                                "TOCARA (CANADA)",
                                "TOM JAMES",
                                "TOTAL LIFE CHANGES/TLC",
                                "TOUCHSTONE CRYSTAL",
                                "TOUCHSTONE ESSENTIALS",
                                "TRACY NEGOSHIAN",
                                "TRADES OF HOPE",
                                "TRANONT",
                                "TRANSFORMATIONAL BEAUTY",
                                "TRAVEL EVOLUTION",
                                "TRAVELING VINEYARD",
                                "TRAVERUS GLOBAL",
                                "TRIVITA",
                                "TROPIC SKIN CARE",
                                "TRUE PEAK REVOLUTION",
                                "TRUVISION HEALTH",
                                "TS-LIFE",
                                "TUPPERWARE",
                                "UNICITY",
                                "UNITED SCIENCES OF",
                                "UNITED WAREHOUSE (UK)",
                                "US HEALTH ADVISORS",
                                "USANA",
                                "USBORNE",
                                "UTILITY WAREHOUSE (UK)",
                                "VALENTUS",
                                "VANTEL",
                                "VASAYO",
                                "VECTOR/CUTCO",
                                "VEMMA",
                                "VIAONEHOPE",
                                "VIBELLA",
                                "VIC COSMETICS",
                                "VIDA DIVINA",
                                "VIE AT HOME",
                                "VIRTUITY FINANCIAL GROUP",
                                "VISALUS (BODY BY",
                                "VITALITY EXTRACTS",
                                "VIVAMK",
                                "VOLO",
                                "VORWERK",
                                "VOTRE BELLE MAISON",
                                "VOXXLIFE",
                                "WAKAYA PERFECTION",
                                "WAKEUPNOW (DISSOLVED 2015)",
                                "WATKINS INC",
                                "WEALTHPERX",
                                "WIKANIKO",
                                "WILDTREE",
                                "WILLING BEAUTY",
                                "WINASUN",
                                "WINE SHOP AT",
                                "WINES FOR HUMANITY",
                                "WINK NATURALS",
                                "WORLD FINANCIAL GROUP/PINNACLE",
                                "WORLD LEADERSHIP GROUP",
                                "WORLD VENTURES/WEALTH WAVE/TKO",
                                "WOTABU",
                                "XANGO/ZIJI",
                                "XERVEO",
                                "XOOM ENERGY",
                                "XOOMA",
                                "XSTREAM TRAVEL",
                                "XYNGULAR",
                                "YANBAL INT",
                                "YANDI (CHINA)",
                                "YELLOOW",
                                "YEVO (CLOSED)",
                                "YOFOTO (CHINA)",
                                "YOLI",
                                "YOONLA",
                                "YOR HEALTH",
                                "YOUNG LIVING",
                                "YOUNGEVITY",
                                "YOUNIQUE",
                                "YTB INTERNATIONAL",
                                "ZEPTER",
                                "ZIJA",
                                "ZILIS",
                                "ZINZINO (SCANDANAVIA)",
                                "ZRII",
                                "ZURVITA",
                                "ZYIA",
                                          "ZYN"]



    
    @IBOutlet weak var YesOrNo: UILabel!
    
    @IBOutlet weak var compnaySearch: UITextField!
    
    
    @IBAction func txtChanged(_ sender: UITextField) {
        
 
        
        
        var resultsForSearch = MLMCompanies_regular.contains(compnaySearch.text!.uppercased())
        if (resultsForSearch == true) {
            companyIsMLM()
        } else {
            companyIsNotMLM()
        }
        
        
    }
    

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    
    func companyIsMLM() {
        
        self.view.backgroundColor = UIColor.red
        YesOrNo.text = "YES"

    }
    
    
    
    func companyIsNotMLM() {
        
        self.view.backgroundColor = UIColor.green
        YesOrNo.text = "NO"

    }
    
    

    


}

